[package]
name = "monad-virtual-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# this is necessary for bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[dev-dependencies]
monad-block-sync = { path = "../monad-block-sync" }
monad-consensus-state = { path = "../monad-consensus-state" }
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-executor = { path = "../monad-executor" }
monad-executor-glue = { path = "../monad-executor-glue" }
monad-gossip = { path = "../monad-gossip" }
monad-mock-swarm = { path = "../monad-mock-swarm" }
monad-quic = { path = "../monad-quic" }
monad-state = { path = "../monad-state" }
monad-testutil = { path = "../monad-testutil" }
monad-types = { path = "../monad-types" }
monad-validator = { path = "../monad-validator" }
monad-wal = { path = "../monad-wal" }


[[bench]]
name = "two_node_bench"
harness = false

[[bench]]
name = "many_nodes_bench"
harness = false
