[package]
name = "monad-consensus-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = { workspace = true, features = ["serde"] }
log = { workspace = true }
prost = { workspace = true, optional = true }
serde_cbor = { workspace = true }
sha2 = { workspace = true }
zerocopy = { workspace = true }

monad-crypto = { path = "../monad-crypto" }
monad-proto = { path = "../monad-proto", optional = true }
monad-types = { path = "../monad-types" }

[features]
proto = [
    "dep:monad-proto",
    "dep:prost",
    "monad-crypto/proto",
    "monad-types/proto",
]

[dev-dependencies]
monad-testutil = { path = "../monad-testutil" }
rand = { workspace = true }
rand_chacha = { workspace = true }
test-case = { workspace = true }
