[package]
name = "monad-node-config"
version = "0.1.0"
edition = "2021"

[dependencies]
monad-crypto = { path = "../monad-crypto" }
monad-eth-types = { path = "../monad-eth-types" }
monad-types = { path = "../monad-types" }

alloy-primitives = { workspace = true }
serde = { workspace = true }
