[package]
name = "monad-node-config"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[dependencies]
monad-bls = { workspace = true, optional = true }
monad-consensus-types = { workspace = true }
monad-crypto = { workspace = true }
monad-eth-types = { workspace = true }
monad-secp = { workspace = true }
monad-types = { workspace = true }

alloy-primitives = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
monad-chain-config = { workspace = true }

clap = { workspace = true }
codespan-reporting = { workspace = true }
strum = { workspace = true, features = ["derive"] }
toml = { workspace = true }

[features]
crypto = ["dep:monad-bls"]

[[example]]
name = "monad-node-config-linter"
path = "examples/linter.rs"
