[package]
name = "monad-executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[dependencies]
monad-crypto = { path = "../monad-crypto" }
monad-proto = { path = "../monad-proto", optional = true }
monad-wal = { path = "../monad-wal" }
monad-types = { path = "../monad-types"  }

futures = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
tokio = { workspace = true, features = ["time"], optional = true }
tracing = { workspace = true }

[dev-dependencies]
monad-testutil = { path = "../monad-testutil" }


tokio = { workspace = true, features = ["macros", "rt"] }

[features]
proto = ["dep:monad-proto", "monad-crypto/proto"]
