[package]
name = "monad-executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
monad-crypto = { path = "../monad-crypto" }

tokio = { version = "1.26", features = ["time"], optional = true }

[dev-dependencies]
monad-testutil = { path = "../monad-testutil"}