services:
  build_monad_execution:
    image: monad-execution-builder:latest
    build:
      context: ${MONAD_BFT_ROOT}/monad-cxx/monad-execution
      dockerfile: docker/release.Dockerfile
      args:
        GIT_COMMIT_HASH: ${GIT_COMMIT_HASH:-$(git rev-parse HEAD)}

  build_triedb:
    image: monad-execution-builder:latest
    command: monad_mpt --storage /monad/triedb/test.db --create
    depends_on:
      - build_monad_execution
    volumes:
      - ./node:/monad
    security_opt:
      - "seccomp:${MONAD_BFT_ROOT}/docker/devnet/monad/config/profile.json"

  build_python:
    build:
      context: ${FLEXNET_IMAGE_ROOT}/python
      dockerfile: ${FLEXNET_IMAGE_ROOT}/python/Dockerfile
    image: monad-python:latest

  monad_execution:
    image: monad-execution-builder:latest
    command: test_run_loop --db /monad/triedb/test.db --block_db /monad/ledger --genesis_file /monad/config/genesis.json --log_level ERROR
    depends_on:
      - build_monad_execution
      - build_triedb
    volumes:
      - ./node:/monad
    security_opt:
      - "seccomp:${MONAD_BFT_ROOT}/docker/devnet/monad/config/profile.json"

  monad_node:
    build:
      context: ${MONAD_BFT_ROOT}
      dockerfile: ${DEVNET_DIR}/Dockerfile
    depends_on:
      - monad_execution
    environment:
      - RUST_LOG=
    volumes:
      - ./node:/monad

  monad_rpc:
    build:
      context: ${MONAD_BFT_ROOT}
      dockerfile: ${RPC_DIR}/Dockerfile
    depends_on:
      - monad_node
    volumes:
      - ./node:/monad
    security_opt:
      - "seccomp:${MONAD_BFT_ROOT}/docker/devnet/monad/config/profile.json"
    ports:
      - "8080:8080"

  e2e_tester:
    image: monad-python:latest
    volumes:
      - ./e2e_tester:/monad
      - ./data:/data
    depends_on:
      - monad_rpc
    entrypoint: ["bash", "/monad/scripts/run.sh"]

networks:
  default:
    driver: bridge
