services:
  build_monad_bft:
    build:
      context: ${MONAD_BFT_ROOT}
      dockerfile: ${FLEXNET_IMAGE_ROOT}/monad-bft-builder/Dockerfile
    image: monad-bft-builder:latest

  runner_python:
    build:
      context: ${FLEXNET_IMAGE_ROOT}/python
      dockerfile: ${FLEXNET_IMAGE_ROOT}/python/Dockerfile
    image: monad-python:latest

  monad_node:
    build:
      context: ${MONAD_BFT_ROOT}
      dockerfile: ${DEVNET_DIR}/Dockerfile
    environment:
      - RUST_LOG=
    volumes:
      - ./node:/monad

  monad_rpc:
    build:
      context: ${MONAD_BFT_ROOT}
      dockerfile: ${RPC_DIR}/Dockerfile
    depends_on:
      - monad_node
    volumes:
      - ./node:/monad
    ports:
      - "8080:8080"

  rpc_blaster:
    image: monad-python:latest
    volumes:
      - ./rpc_blaster:/monad
      - ./data:/data
    entrypoint: ["bash", "/monad/scripts/run.sh"]

networks:
  default:
    driver: bridge
