[package]
name = "monad-viz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.21"
egui-macroquad = "0.15"
macroquad = { version = "0.3.25", default-features = false }

monad-executor = { path = "../monad-executor" }
monad-consensus = { path = "../monad-consensus" }
monad-crypto = { path = "../monad-crypto" }
monad-state = { path = "../monad-state" }
monad-testutil = { path = "../monad-testutil" }
