[package]
name = "monad-viz"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "monad-viz"
bench = false

[dependencies]
monad-consensus-state = { path = "../monad-consensus-state" }
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-eth-types = { path = "../monad-eth-types" }
monad-executor = { path = "../monad-executor" }
monad-executor-glue = { path = "../monad-executor-glue" }
monad-mock-swarm = { path = "../monad-mock-swarm" }
monad-router-scheduler = { path = "../monad-router-scheduler" }
monad-state = { path = "../monad-state" }
monad-testutil = { path = "../monad-testutil" }
monad-transformer = { path = "../monad-transformer" }
monad-types = { path = "../monad-types" }
monad-updaters = { path = "../monad-updaters" }
monad-validator = { path = "../monad-validator" }
monad-wal = { path = "../monad-wal" }

clap = { workspace = true, features = ["derive"] }
iced = { workspace = true, features = ["canvas"] }
iced_native = { workspace = true }
iced_lazy = { workspace = true }
