[package]
name = "monad-viz"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "monad-viz"
bench = false

[dependencies]
monad-block-sync = { path = "../monad-block-sync" }
monad-consensus-state = { path = "../monad-consensus-state" }
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-executor = { path = "../monad-executor" }
monad-state = { path = "../monad-state" }
monad-testutil = { path = "../monad-testutil" }
monad-types = { path = "../monad-types" }
monad-validator = { path = "../monad-validator" }
monad-wal = { path = "../monad-wal" }

iced = { version = "0.9", features = ["canvas"] }
iced_native = { version = "0.10" }
iced_lazy = { version = "0.6" }
clap = {version = "4.3.11", features= ["derive"] }

