[workspace]

members = [
    "monad-blocktree",
    "monad-consensus",
    "monad-crypto",
    "monad-driver",
    "monad-executor", 
    "monad-node",
    "monad-p2p",
    "monad-proto",
    "monad-randomized-tests",
    "monad-state",
    "monad-testutil",
    "monad-tracing-counter",
    "monad-types",
    "monad-validator",
    "monad-viz",
    "monad-wal",
]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.release]
debug = true

[workspace.dependencies]
libp2p = { git = "https://github.com/monad-crypto/rust-libp2p.git", rev = "a2a5160b" }
libp2p-identity = { git = "https://github.com/monad-crypto/rust-libp2p.git", rev = "a2a5160b" }

async-trait = "0.1"
clap = "4.2"
criterion = "0.4.0"
futures = "0.3"
futures-util = "0.3"
hex = "0.4"
itertools = "0.10.5"
log = "0.4"
multihash = "0.17"
opentelemetry = "0.19"
opentelemetry-contrib = "0.11"
prost = "0.11.9"
prost-build = "0.11.9"
protobuf-src = "1.1.0"
ptree = "0.4.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
ref-cast = "1.0"
secp256k1 = "0.26"
sha2 = "0.10.6"
tempfile = "3.5.0"
test-case = "3.0.0"
tiny-keccak = "2.0"
tokio = "1.28.2"
tracing = "0.1.37"
tracing-core = "0.1.30"
tracing-opentelemetry = "0.19"
tracing-subscriber = "0.3.17"
zerocopy = "0.6.1"
zeroize = "1.3"
