[workspace]

members = [
    "monad-async-state-verify",
    "monad-blockdb",
    "monad-blockdb-utils",
    "monad-blocktree",
    "monad-bls",
    "monad-control-panel",
    "monad-compress",
    "monad-consensus",
    "monad-consensus-state",
    "monad-consensus-types",
    "monad-crypto",
    "monad-cxx",
    "monad-dataplane",
    "monad-debugger",
    "monad-eth-block-policy",
    "monad-eth-block-validator",
    "monad-eth-testutil",
    "monad-eth-types",
    "monad-eth-tx",
    "monad-eth-txpool",
    "monad-eth-types",
    "monad-executor",
    "monad-executor-glue",
    "monad-gossip",
    "monad-ipc",
    "monad-keystore",
    "monad-ledger",
    "monad-mock-swarm",
    "monad-triedb",
    "monad-multi-sig",
    "monad-node",
    "monad-perf-util",
    "monad-proto",
    "monad-quic",
    "monad-randomized-tests",
    "monad-raptorcast",
    "monad-router-scheduler",
    "monad-rpc",
    "monad-secp",
    "monad-state",
    "monad-testground",
    "monad-testutil",
    "monad-tracing-counter",
    "monad-transformer",
    "monad-triedb-utils",
    "monad-twins",
    "monad-types",
    "monad-updaters",
    "monad-validator",
    "monad-virtual-bench",
    "monad-wal",
]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.release]
debug = true
panic = "abort"

[workspace.dependencies]
reth-primitives = { git = "https://github.com/paradigmxyz/reth.git", rev = "685d1c5", default-features = false }
reth-rpc-types = { git = "https://github.com/paradigmxyz/reth.git", rev = "685d1c5", default-features = false }
alloy-primitives = "0.6"
alloy-rlp = "0.3"

actix = "0.13"
actix-codec = "0.5"
actix-http = "3.6.0"
actix-web = "4.5.1"
actix-web-actors = "4.3.0"
actix-http-test = "3.2"
actix-test = "0.1"
aes = "0.8.3"
as-any = "0.3.1"
async-trait = "0.1"
autocxx = "0.26"
autocxx-build = "0.26"
bindgen = "0.69"
bincode = "1.3"
bitvec = "1.0"
blake3 = "1.5"
blst = "0.3"
brotli = "3.4"
bytes = "1.5"
bytes-utils = "0.1"
cc = "1.0"
chrono = "0.4.34"
clap = "4.2"
cmake = "0.1"
console_error_panic_hook = "0.1"
criterion = { version = "0.4", features = ["html_reports"] }
ctr = "0.9.2"
cxx = "1.0"
dialoguer = "0.10"
env_logger = "0.10"
fastrand = "2.0"
flate2 = "1.0"
flume = "0.11.0"
futures = "0.3"
futures-util = "0.3"
getrandom = "0.2"
hdwallet = "0.4.1"
heed = "0.11.0"
hex = "0.4"
hex-literal = "0.4"
inventory = "0.3"
inquire = "0.7"
itertools = "0.10"
async-graphql = "7.0"
libc = "0.2.153"
log = "0.4"
lz4 = "1.24"
multihash = "0.17"
ntest = "0.9"
opentelemetry = "0.24"
opentelemetry-otlp = "0.17"
opentelemetry-semantic-conventions = "0.16"
opentelemetry_sdk = "0.24"
pbkdf2 = "0.12"
peak_alloc = "0.2"
priority-queue = "1.3"
prost = "0.11"
prost-build = "0.11"
prost-types = "0.11"
protobuf-src = "1.1"
crossterm = "0.27.0"
ratatui = "0.26.0"

quinn = { git = "https://github.com/omegablitz/quinn.git", rev = "0780497b" }
quinn-proto = { git = "https://github.com/omegablitz/quinn.git", rev = "0780497b" }

rand = "0.8"
rand_chacha = "0.3"
raptor-code = { git = "https://github.com/omegablitz/raptor", rev = "8cdd8fcc" }
raptorq = "1.8"
rayon = "1.7"
rcgen = "0.11"
reqwest = { version = "0.11", features = ["json"] }
ring = "0.17"
rtrb = "0.3"
rustls = "0.21"
scrypt = { version = "0.11", default-features = false }
secp256k1 = "0.26"
serde = "1.0"
serde_cbor = "0.11"
serde_json = "1.0"
sha2 = "0.10"
simple-xml-builder = "1.1"
socket2 = "0.5.6"
sorted_vector_map = "0.2.0"
tempfile = "3.5"
test-case = "3.0"
thiserror = "1.0"
tiny-bip39 = "1.0"
tiny-keccak = "2"
tokio = "1.36"
tokio-util = "0.7"
toml = "0.7"
tracing = "0.1"
tracing-core = "0.1"
tracing-opentelemetry = "0.25"
tracing-subscriber = "0.3"
tracing-test = "0.2"
wasm-bindgen = "0.2"
x509-parser = "0.15"
zerocopy = "0.6"
zeroize = "1.3"
