[workspace]

members = [
    "monad-blocktree",
    "monad-consensus",
    "monad-crypto",
    "monad-executor",
    "monad-proto",
    "monad-state",
    "monad-testutil",
    "monad-types",
    "monad-validator",
    "monad-viz",
]

[profile.dev]
opt-level = 1
