[workspace]

members = [
    "monad-blocktree",
    "monad-consensus",
    "monad-crypto",
    "monad-driver",
    "monad-executor", 
    "monad-node",
    "monad-p2p",
    "monad-proto",
    "monad-state",
    "monad-testutil",
    "monad-types",
    "monad-validator",
    "monad-viz",
    "monad-wal",
]
resolver = "2"

[profile.dev]
opt-level = 1

[workspace.dependencies]
libp2p = { git = "https://github.com/monad-crypto/rust-libp2p.git", rev = "a2a5160b" }
libp2p-identity = { git = "https://github.com/monad-crypto/rust-libp2p.git", rev = "a2a5160b" }
