[workspace]

members = [
    "monad-blocktree",
    "monad-consensus",
    "monad-consensus-types",
    "monad-crypto",
    "monad-driver",
    "monad-executor",
    "monad-mempool-checker",
    "monad-mempool-controller",
    "monad-mempool-messenger",
    "monad-mempool-node",
    "monad-mempool-server",
    "monad-mempool-txpool",
    "monad-mempool-types",
    "monad-node",
    "monad-p2p",
    "monad-proto",
    "monad-randomized-tests",
    "monad-state",
    "monad-testutil",
    "monad-tracing-counter",
    "monad-types",
    "monad-validator",
    "monad-viz",
    "monad-wal",
]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.release]
debug = true

[workspace.dependencies]
libp2p = { git = "https://github.com/monad-crypto/rust-libp2p.git", rev = "8ca605d9" }
libp2p-identity = { git = "https://github.com/monad-crypto/rust-libp2p.git", rev = "8ca605d9" }

async-trait = "0.1"
axum = "0.6.12"
blst = "0.3.10"
clap = "4.2"
criterion = "0.4.0"
ethers = "2.0.2"
futures = "0.3"
futures-util = "0.3"
hex = "0.4.3"
itertools = "0.10.5"
log = "0.4"
multihash = "0.17"
oorandom = "11.1.3"
opentelemetry = "0.19"
opentelemetry_api = "0.19"
opentelemetry-otlp = "0.12"
opentelemetry-semantic-conventions = "0.11"
prost = "0.11.9"
prost-build = "0.11.9"
prost-types = "0.11.8"
protobuf-src = "1.1.0"
ptree = "0.4.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
ref-cast = "1.0"
secp256k1 = "0.26"
serde = "1.0.160"
serde_json = "1.0.95"
sha2 = "0.10.6"
tempfile = "3.5.0"
test-case = "3.0.0"
thiserror = "1.0.40"
tiny-keccak = "2.0"
tokio = "1.28.2"
tracing = "0.1.37"
tracing-core = "0.1.30"
tracing-opentelemetry = "0.19"
tracing-subscriber = "0.3.17"
zerocopy = "0.6.1"
zeroize = "1.3"
