[workspace]

members = [
    "monad-block-sync",
    "monad-blocktree",
    "monad-consensus",
    "monad-consensus-state",
    "monad-consensus-types",
    "monad-crypto",
    "monad-driver",
    "monad-eth-types",
    "monad-executor",
    "monad-executor-glue",
    "monad-gossip",
    "monad-ledger",
    "monad-mempool-controller",
    "monad-mempool-ipc",
    "monad-mempool-messenger",
    "monad-mempool-proto",
    "monad-mempool-testutil",
    "monad-mempool-txpool",
    "monad-mempool-types",
    "monad-mock-swarm",
    "monad-node",
    "monad-p2p",
    "monad-proto",
    "monad-quic",
    "monad-randomized-tests",
    "monad-state",
    "monad-testground",
    "monad-testutil",
    "monad-tracing-counter",
    "monad-twins",
    "monad-types",
    "monad-updaters",
    "monad-validator",
    "monad-virtual-bench",
    "monad-viz",
    "monad-wal",
]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.release]
debug = true

[workspace.dependencies]
libp2p = { git = "https://github.com/monad-crypto/rust-libp2p.git", rev = "8ca605d9" }
libp2p-identity = { git = "https://github.com/monad-crypto/rust-libp2p.git", rev = "8ca605d9" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth.git", rev = "b701cbc" }
reth-rlp = { git = "https://github.com/paradigmxyz/reth.git", rev = "b701cbc" }

async-trait = "0.1"
bitvec = "1.0.1"
blake3 = "1.5"
blst = "0.3.11"
bytes = "1.5.0"
clap = "4.2"
criterion = "0.4.0"
env_logger = "0.10"
futures = "0.3"
futures-util = "0.3"
hex = "0.4.3"
itertools = "0.10.5"
log = "0.4"
multihash = "0.17"
opentelemetry = "0.19"
opentelemetry_api = "0.19"
opentelemetry-otlp = "0.12"
opentelemetry-semantic-conventions = "0.11"
prost = "0.11.9"
prost-build = "0.11.9"
prost-types = "0.11.8"
protobuf-src = "1.1.0"
ptree = { version = "0.4.0", default-features = false }

# the important commit: "dd34d57a0a184ae23707d5ae045ec62d8f0b6ecb"
# we can use latest release once it includes that
quinn = { git = "https://github.com/quinn-rs/quinn.git", rev = "dd34d57a" }
quinn-proto = { git = "https://github.com/quinn-rs/quinn.git", rev = "dd34d57a" }

rand = "0.8.5"
rand_chacha = "0.3.1"
rayon = "1.7"
rcgen = "0.11"
ref-cast = "1.0"
rustls-pemfile = "1.0.3"
rustls = "0.21"
secp256k1 = "0.26"
serde = "1.0.160"
serde_cbor = "0.11.2"
sha2 = "0.10.6"
tempfile = "3.5.0"
test-case = "3.0.0"
thiserror = "1.0.40"
tiny-keccak = "2.0"
tokio = "1.28.2"
tokio-util = "0.7.8"
toml = "0.7.6"
tracing = "0.1.37"
tracing-core = "0.1.30"
tracing-opentelemetry = "0.19"
tracing-subscriber = "0.3.17"
tracing-test = "0.2.4"
x509-parser = "0.15"
zerocopy = "0.6.1"
zeroize = "1.3"
