[workspace]

members = [
    "monad-blocktree",
    "monad-compress",
    "monad-consensus",
    "monad-consensus-state",
    "monad-consensus-types",
    "monad-crypto",
    "monad-eth-types",
    "monad-executor",
    "monad-executor-glue",
    "monad-gossip",
    "monad-ledger",
    "monad-mempool-controller",
    "monad-mempool-ipc",
    "monad-mempool-messenger",
    "monad-mempool-proto",
    "monad-mempool-testutil",
    "monad-mempool-txpool",
    "monad-mempool-types",
    "monad-mock-swarm",
    "monad-node",
    "monad-proto",
    "monad-quic",
    "monad-randomized-tests",
    "monad-router-scheduler",
    "monad-state",
    "monad-testground",
    "monad-testutil",
    "monad-tracing-counter",
    "monad-transformer",
    "monad-twins",
    "monad-types",
    "monad-updaters",
    "monad-validator",
    "monad-virtual-bench",
    "monad-viz",
    "monad-wal",
]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.release]
debug = true

[workspace.dependencies]
libp2p = "0.52"
reth-primitives = { git = "https://github.com/paradigmxyz/reth.git", rev = "b701cbc" }
reth-rlp = { git = "https://github.com/paradigmxyz/reth.git", rev = "b701cbc" }

async-trait = "0.1"
base64 = "0.21"
bincode = "1.3"
bitvec = "1.0"
blake3 = "1.5"
blst = "0.3"
brotli = "3.4"
bytes = "1.5"
bytes-utils = "0.1"
clap = "4.2"
criterion = "0.4"
env_logger = "0.10"
fastrand = "2.0"
flate2 = "1.0"
futures = "0.3"
futures-util = "0.3"
hex = "0.4"
iced = "0.9"
iced_lazy = "0.6"
iced_native = "0.10"
inventory = "0.3"
itertools = "0.10"
log = "0.4"
lz4 = "1.24"
multihash = "0.17"
opentelemetry = "0.19"
opentelemetry_api = "0.19"
opentelemetry-otlp = "0.12"
opentelemetry-semantic-conventions = "0.11"
peak_alloc = "0.2"
priority-queue = "1.3"
prost = "0.11"
prost-build = "0.11"
prost-types = "0.11"
protobuf-src = "1.1"

# the important commit: "dd34d57a0a184ae23707d5ae045ec62d8f0b6ecb"
# we can use latest release once it includes that
quinn = { git = "https://github.com/quinn-rs/quinn.git", rev = "dd34d57a" }
quinn-proto = { git = "https://github.com/quinn-rs/quinn.git", rev = "dd34d57a" }

rand = "0.8"
rand_chacha = "0.3"
rayon = "1.7"
rcgen = "0.11"
ring = "0.17"
rustls = "0.21"
secp256k1 = "0.26"
serde = "1.0"
serde_cbor = "0.11"
serde_json = "1.0"
sha2 = "0.10"
simple-xml-builder = "1.1"
tempfile = "3.5"
test-case = "3.0"
thiserror = "1.0"
tiny-keccak = "2"
tokio = "1.28"
tokio-util = "0.7"
toml = "0.7"
tracing = "0.1"
tracing-core = "0.1"
tracing-opentelemetry = "0.19"
tracing-subscriber = "0.3"
tracing-test = "0.2"
x509-parser = "0.15"
zerocopy = "0.6"
zeroize = "1.3"
ntest = "0.9"
