name = "rs"
workdir = "/tmp/rs10-2mb"

[network]
cidr = "10.1.0.0/24"

[latency]
type = "auto"
local = "10ms"
distanced = "30ms"
buckets = 5

[[guests.commands]]
command = "/home/dd/monad-bft/target/release/node producer --cluster /home/dd/monad-bft/cluster.toml --interval 2s --size 2MB"
[guests.commands.env]
RUST_LOG = "info"

[[guests.commands]]
command = "/home/dd/monad-bft/target/release/node run --cluster /home/dd/monad-bft/cluster.toml"
replicas = 9
[guests.commands.env]
RUST_LOG = "info"