[package]
name = "monad-triedb-utils"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[dependencies]
monad-eth-types = { workspace = true }
monad-state-backend = { workspace = true }
monad-triedb = { workspace = true }
monad-types = { workspace = true }

alloy-consensus = { workspace = true, features = ["serde"] }
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
monad-eth-testutil = { workspace = true }

clap = { workspace = true, features = ["derive"] }
hex = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }
