
#########################################################
#                                                       #
#        WARNING: THIS FILE SHOULD NEVER BE USED        #
#              IN PRODUCTION ENVIRONMENTS!              #
#                                                       #
#########################################################

beneficiary = "0x0000000000000000000000000000000000000000"

[[bootstrap.peers]]
address = "node0_us:8888"
mempool_address = "node0_us:8889"
secp256k1_pubkey = "0x02b0b53e1c8132629cac9dc52357f3867576a29fba4fc686501caa8b7c21992612"

[[bootstrap.peers]]
address = "node2_eu:8888"
mempool_address = "node2_eu:8889"
secp256k1_pubkey = "0x03521142713b444ebab11ade695747e1cad3c6a11f5a5b451f99419b1f88d4932f"

[network]
bind_address_host = "0.0.0.0"
bind_address_port = 8888
max_rtt_ms = 300
max_mbps = 1000
