[package]
name = "monad-crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1 = { version = "0.26", features = ["global-context", "recovery"] }
sha2 = "0.10"

[dev-dependencies]
hex = "0.4"
tiny-keccak = { version = "2.0", features = ["keccak"] }
