[package]
name = "monad-crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
secp256k1 = { version = "0.26", features = ["global-context", "recovery"] }
sha2 = "0.10"
zeroize = "1.3"

libp2p-identity = { version = "0.1", features = ["secp256k1"], optional = true }
multihash = { version = "0.17", features = ["identity"], optional = true }

[dev-dependencies]
hex = "0.4"
tiny-keccak = { version = "2.0", features = ["keccak"] }

[features]
libp2p-identity = ["dep:libp2p-identity", "dep:multihash"]
