[package]
name = "monad-tracing-counter"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { workspace = true }
tracing-core = { workspace = true }
tracing-subscriber = { workspace = true }

