[package]
name = "monad-testground"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "monad-testground"
bench = false

[dependencies]
monad-consensus-state = { path = "../monad-consensus-state" }
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-eth-types = { path = "../monad-eth-types" }
monad-executor = { path = "../monad-executor" }
monad-executor-glue = { path = "../monad-executor-glue" }
monad-gossip = { path = "../monad-gossip" }
monad-mock-swarm = { path = "../monad-mock-swarm" }
monad-quic = { path = "../monad-quic" }
monad-state = { path = "../monad-state" }
monad-types = { path = "../monad-types" }
monad-updaters = { path = "../monad-updaters", features = ["tokio"] }
monad-validator = { path = "../monad-validator" }

clap = { workspace = true, features = ["derive"] }
env_logger = { workspace = true }
futures-util = { workspace = true }
opentelemetry = { workspace = true, features = ["rt-tokio"] }
opentelemetry_api = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry-semantic-conventions = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true, features = ["log"] }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }
