[package]
name = "monad-quic"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monad-crypto = { path = "../monad-crypto", features = ["rustls"] }
monad-executor-glue = { path = "../monad-executor-glue" }
monad-gossip = { path = "../monad-gossip" }
monad-executor = { path = "../monad-executor" }
monad-router-scheduler = { path = "../monad-router-scheduler" }
monad-types = { path = "../monad-types" }

futures = { workspace = true }
tokio = { workspace = true, features = ["time"] }
tracing = { workspace = true }

quinn = { workspace = true }
quinn-proto = { workspace = true }

rand = { workspace = true }

[dev-dependencies]
clap = { workspace = true, features = ["derive"] }
env_logger = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }

[[example]]
name = "service"
