[package]
name = "monad-proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monad-consensus = { path = "../monad-consensus" }
monad-crypto = { path = "../monad-crypto" }
monad-types = { path = "../monad-types" }

prost = "0.11"
zerocopy = "0.6.1"

[build-dependencies]
prost-build = "0.11"
protobuf-src = "1.1.0"

[dev-dependencies]
monad-testutil = { path = "../monad-testutil" }

monad-validator = { path = "../monad-validator" }
