[package]
name = "monad-state"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monad-blocktree = { path = "../monad-blocktree" }
monad-consensus = { path = "../monad-consensus" }
monad-crypto = { path = "../monad-crypto" }
monad-executor = { path = "../monad-executor" }
monad-types = { path = "../monad-types" }
monad-validator = { path = "../monad-validator" }

[dev-dependencies]
monad-testutil = { path = "../monad-testutil"}
