[package]
name = "monad-state"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[dependencies]
monad-blocktree = { path = "../monad-blocktree" }
monad-consensus = { path = "../monad-consensus" }
monad-crypto = { path = "../monad-crypto" }
monad-executor = { path = "../monad-executor" }
monad-types = { path = "../monad-types" }
monad-validator = { path = "../monad-validator" }

monad-proto = { path = "../monad-proto", optional = true }

ref-cast = "1.0"

[features]
proto = ["dep:monad-proto"]

[dev-dependencies]
monad-testutil = { path = "../monad-testutil"}
criterion = "0.4"

[[bench]]
name = "two_node_benchmark"
harness = false
