[package]
name = "monad-state"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[dependencies]
monad-blocksync = { path = "../monad-blocksync" }
monad-blocktree = { path = "../monad-blocktree" }
monad-chain-config = { path = "../monad-chain-config" }
monad-consensus = { path = "../monad-consensus" }
monad-consensus-state = { path = "../monad-consensus-state" }
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-executor-glue = { path = "../monad-executor-glue" }
monad-proto = { path = "../monad-proto" }
monad-state-backend = { path = "../monad-state-backend" }
monad-types = { path = "../monad-types" }
monad-validator = { path = "../monad-validator" }

alloy-rlp = { workspace = true }
bytes = { workspace = true }
itertools = { workspace = true }
prost = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
monad-bls = { path = "../monad-bls" }
monad-eth-types = { path = "../monad-eth-types" }
monad-secp = { path = "../monad-secp" }
monad-testutil = { path = "../monad-testutil" }

toml = { workspace = true }
tracing = { workspace = true }
