[package]
name = "monad-testutil"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[dependencies]
monad-consensus = { path = "../monad-consensus" }
monad-consensus-state = { path = "../monad-consensus-state" }
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-eth-types = { path = "../monad-eth-types" }
monad-executor-glue = { path = "../monad-executor-glue" }
monad-state = { path = "../monad-state" }
monad-mock-swarm = { path = "../monad-mock-swarm" }
monad-types = { path = "../monad-types" }
monad-validator = { path = "../monad-validator" }

zerocopy = { workspace = true }

[dev-dependencies]
monad-block-sync = { path = "../monad-block-sync" }
monad-executor = { path = "../monad-executor" }
monad-wal = { path = "../monad-wal" }
