[package]
name = "monad-consensus-state"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[dependencies]
monad-blocktree = { path = "../monad-blocktree" }
monad-consensus = { path = "../monad-consensus" }
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-eth-types = { path = "../monad-eth-types" }
monad-types = { path = "../monad-types" }
monad-tracing-counter = { path = "../monad-tracing-counter" }
monad-validator = { path = "../monad-validator" }

tracing = { workspace = true }

[dev-dependencies]
monad-testutil = { path = "../monad-testutil" }

env_logger = { workspace = true }
itertools = { workspace = true }
test-case = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-test = { workspace = true }
