[package]
name = "monad-message-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "0.4.0", features = ["arbitrary-derive"] }
monad-types = { path = "../../monad-types" }
arbitrary = { version = "1", optional = true, features = ["derive"] }
monad-consensus-types = { path = "../../monad-consensus-types" }
monad-crypto = { path = "../../monad-crypto" }
monad-proto = { path = "../../monad-proto" }
monad-validator = { path = "../../monad-validator" }
monad-eth-types = { path = "../../monad-eth-types" }
monad-multi-sig = { path = "../../monad-multi-sig" }
monad-state = { path = "../../monad-state" }
monad-testutil = { path = "../../monad-testutil" }
monad-consensus = { path = "../" }


[[bin]]
name = "fuzz_verify"
path = "fuzz_targets/fuzz_verify.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_validate"
path = "fuzz_targets/fuzz_validate.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_validate_tc"
path = "fuzz_targets/fuzz_validate_tc.rs"
test = false
doc = false
bench = false
