
#########################################################
#                                                       #
#        WARNING: THIS FILE SHOULD NEVER BE USED        #
#              IN PRODUCTION ENVIRONMENTS!              #
#                                                       #
#########################################################

beneficiary = "0x025c49a4d358de6a5f7f183c494c1d76a5fad285"

[[bootstrap.peers]]
address = "node0:8888"
mempool_address = "node0:8889"
secp256k1_pubkey = "0x03867f9709744698e0c140c309d93baf53655176b215931de52ff6f371101c02a9"

[[bootstrap.peers]]
address = "node1:8888"
mempool_address = "node1:8889"
secp256k1_pubkey = "0x037743e7be2ed992769ac12d122b93cf80c1a5ff0a5dcdfe26bdd347c372520964"

[[bootstrap.peers]]
address = "node2:8888"
mempool_address = "node2:8889"
secp256k1_pubkey = "0x0332286e8e0a1b4ad9dd76a122c1628c79df51954e950aebc3a1d4ff03b3a2568a"

[network]
bind_address_host = "0.0.0.0"
bind_address_port = 8888
max_rtt_ms = 300
max_mbps = 1000
