[package]
name = "monad-twins"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[dev-dependencies]
monad-mock-swarm = { workspace = true }
monad-twins-utils = { workspace = true }

test-case = { workspace = true }
