[package]
name = "monad-updaters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[dependencies]
monad-blocksync = { path = "../monad-blocksync" }
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-eth-block-policy = { path = "../monad-eth-block-policy" }
monad-eth-txpool = { path = "../monad-eth-txpool" }
monad-eth-types = { path = "../monad-eth-types" }
monad-executor = { path = "../monad-executor" }
monad-executor-glue = { path = "../monad-executor-glue" }
monad-node-config = { path = "../monad-node-config" }
monad-state-backend = { path = "../monad-state-backend" }
monad-triedb-utils = { path = "../monad-triedb-utils", optional = true }
monad-types = { path = "../monad-types" }

alloy-consensus = { workspace = true }
alloy-rlp = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
rayon = { workspace = true }
serde_json = { workspace = true }
sorted-vec = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"], optional = true }
toml = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
ntest = { workspace = true }

[features]
monad-triedb = ["dep:monad-triedb-utils"]
