[package]
name = "monad-mock-swarm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[features]
monad_test = [
    "monad-consensus/monad_test",
    "monad-executor-glue/monad_test",
    "monad-state/monad_test",
]

[dependencies]
monad-block-sync = { path = "../monad-block-sync" }
monad-consensus = { path = "../monad-consensus" }
monad-consensus-state = { path = "../monad-consensus-state" }
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-eth-types = { path = "../monad-eth-types" }
monad-executor = { path = "../monad-executor" }
monad-executor-glue = { path = "../monad-executor-glue" }
monad-state = { path = "../monad-state", features = ["monad_test"] }
monad-tracing-counter = { path = "../monad-tracing-counter" }
monad-types = { path = "../monad-types" }
monad-updaters = { path = "../monad-updaters" }
monad-validator = { path = "../monad-validator" }
monad-wal = { path = "../monad-wal" }

futures = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rayon = { workspace = true }
tracing = { workspace = true }
itertools = { workspace = true }

[dev-dependencies]
monad-block-sync = { path = "../monad-block-sync" }
monad-consensus = { path = "../monad-consensus", features = ["monad_test"] }
monad-consensus-state = { path = "../monad-consensus-state", features = [
    "monad_test",
] }
monad-executor = { path = "../monad-executor", features = ["monad_test"] }
monad-gossip = { path = "../monad-gossip" }
monad-mock-swarm = { path = ".", features = ["monad_test"] }
monad-quic = { path = "../monad-quic" }
monad-testutil = { path = "../monad-testutil" }

criterion = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rcgen = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }
tracing = { workspace = true }
tracing-core = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-test = { workspace = true, features = ["no-env-filter"] }

[[bench]]
name = "two_node_benchmark"
harness = false
