[package]
name = "monad-node"
version = "0.1.0"
edition = "2021"

[dependencies]
monad-consensus = { path = "../monad-consensus" }
monad-crypto = { path = "../monad-crypto", features = ["libp2p-identity"] }
monad-executor = { path = "../monad-executor", features = ["tokio"] }
monad-p2p = { path = "../monad-p2p", features = ["tokio"] }
monad-state = { path = "../monad-state", features = ["proto"] }
monad-types = { path = "../monad-types" }

clap = { workspace = true, features = ["derive"] }
futures-util = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

opentelemetry = { workspace = true, features = ["rt-tokio"] }
opentelemetry_api = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry-semantic-conventions = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }
