[package]
name = "monad-blockdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
bench = false

[dependencies]
heed = { workspace = true }
reth-primitives = { workspace = true }
serde = { workspace = true }
