[package]
name = "monad-ipc"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-executor-glue = { path = "../monad-executor-glue" }
monad-eth-types = { path = "../monad-eth-types" }

alloy-consensus = { workspace = true }
alloy-rlp = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "net",
    "rt",
    "time",
] }
tokio-util = { workspace = true, features = ["codec"] }
tracing = { workspace = true }

[dev-dependencies]
monad-bls = { path = "../monad-bls" }
monad-secp = { path = "../monad-secp" }

alloy-consensus = { workspace = true, features = ["k256"] }
alloy-primitives = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
clap = { workspace = true, features = ["derive"] }
hex = { workspace = true }
itertools = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "time"] }
tracing-subscriber = { workspace = true }

[[example]]
name = "ethtx"
