[package]
name = "monad-eth-types"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
serde = { workspace = true, optional = true }

[features]
serde = ["dep:serde"]
