[package]
name = "monad-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { workspace = true }
alloy-rlp = { workspace = true }
clap = { workspace = true, features = ["derive"] }
diesel = { workspace = true, features = ["postgres"] }
diesel-async = { workspace = true, features = ["bb8", "postgres"] }
diesel_migrations = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
inotify = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt"] }
toml = { workspace =  true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

monad-block-persist = { path = "../monad-block-persist" }
monad-bls = { path = "../monad-bls" }
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-eth-types = { path = "../monad-eth-types" }
monad-node-config = { path = "../monad-node-config" }
monad-secp = { path = "../monad-secp" }
monad-types = { path = "../monad-types" }
monad-validator = { path = "../monad-validator" }
