[package]
name = "monad-gossip"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monad-crypto = { path = "../monad-crypto" }
monad-merkle = { path = "../monad-merkle" }
monad-transformer = { path = "../monad-transformer" }
monad-types = { path = "../monad-types" }

bincode = { workspace = true }
bytes = { workspace = true }
bytes-utils = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
raptorq = { workspace = true, features = ["serde_support"] }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
fastrand = { workspace = true }
test-case = { workspace = true }

monad-secp = { path = "../monad-secp" }
monad-virtual-bench = { path = "../monad-virtual-bench" }

[[bench]]
name = "rand_shuffle_bench"
harness = false

[[bench]]
name = "raptor_bench"
harness = false

[[bench]]
name = "devnet_bench"
harness = false

[[bench]]
name = "testnet_bench"
harness = false
