[package]
name = "monad-mempool-messenger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monad-mempool-types = { path = "../monad-mempool-types" }

libp2p = { workspace = true, features = ["dns", "gossipsub", "macros", "mdns", "tcp", "tokio", "yamux", "noise", "websocket", "mplex"] }
prost = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "macros"] }
tracing = { workspace = true }
