[package]
name = "monad-rpc"
description = "Monad JSON-RPC API server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "monad-rpc"
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monad-archive = { path = "../monad-archive" }
monad-cxx = { path = "../monad-cxx" }
monad-eth-txpool-ipc = { path = "../monad-eth-txpool-ipc" }
monad-eth-txpool-types = { path = "../monad-eth-txpool-types" }
monad-eth-types = { path = "../monad-eth-types" }
monad-rpc-docs = { path = "./monad-rpc-docs" }
monad-triedb-utils = { path = "../monad-triedb-utils" }
monad-types = { path = "../monad-types" }

actix = { workspace = true }
actix-http = { workspace = true }
actix-test = { workspace = true }
actix-web = { workspace = true }
actix-web-actors = { workspace = true }
alloy-consensus = { workspace = true, features = ["k256"] }
alloy-eips = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
alloy-rpc-types = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true, features = ["derive"] }
dashmap = { workspace = true }
env_logger = { workspace = true }
flume = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
itertools = { workspace = true }
notify = { workspace = true }
opentelemetry = { workspace = true, features = ["metrics"] }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio"] }
opentelemetry-otlp = { workspace = true }
pin-project = { workspace = true }
rayon = { workspace = true }
schemars = "0.8.21"
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["net", "macros", "rt-multi-thread", "fs"] }
tracing = { workspace = true, features = ["log"] }
tracing-actix-web = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }

[dev-dependencies]
alloy-rpc-client = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
reqwest = { workspace = true }
test-case = { workspace = true }

[build-dependencies]
vergen-git2 = "1.0.5"