[package]
name = "monad-rpc"
description = "Monad JSON-RPC API server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "monad-rpc"
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monad-blockdb = { path = "../monad-blockdb" }
monad-blockdb-utils = { path = "../monad-blockdb-utils" }
monad-cxx = { path = "../monad-cxx" }
monad-triedb = { path = "../monad-triedb" }
monad-triedb-utils = { path = "../monad-triedb-utils" }
monad-types = { path = "../monad-types" }
monad-rpc-docs = { path = "./monad-rpc-docs" }

actix = { workspace = true }
actix-codec = { workspace = true }
actix-http = { workspace = true }
actix-http-test = { workspace = true }
actix-test = { workspace = true }
actix-web = { workspace = true }
actix-web-actors = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true, features = ["derive"] }
env_logger = { workspace = true }
flume = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
reth-primitives = { workspace = true }
reth-rpc-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio-util = { workspace = true, features = ["codec"] }
tokio = { workspace = true, features = ["net", "macros"] }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
notify = "6.1.1"
pin-project = "1.1.5"
schemars = "0.8.21"

[dev-dependencies]
test-case = { workspace = true }
tempfile = { workspace = true }
