[package]
name = "monad-randomized-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-mock-swarm = { path = "../monad-mock-swarm" }
monad-router-scheduler = { path = "../monad-router-scheduler" }
monad-testutil = { path = "../monad-testutil" }
monad-transformer = { path = "../monad-transformer" }
monad-types = { path = "../monad-types" }
monad-wal = { path = "../monad-wal" }

inventory = "0.3.6"
simple-xml-builder = "1.1.0"

[[bin]]
name = "randomized-tests"
path = "src/main.rs"
bench = false
