[package]
name = "monad-randomized-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monad-executor = { path = "../monad-executor" }
monad-testutil = { path = "../monad-testutil" }

inventory = "0.3.6"
simple-xml-builder = "1.1.0"

[[bin]]
name = "randomized-tests"
path = "src/main.rs"
