[package]
name = "monad-statesync"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-executor = { path = "../monad-executor" }
monad-executor-glue = { path = "../monad-executor-glue" }
monad-types = { path = "../monad-types" }

futures = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true, features = ["io-util", "net", "rt", "sync", "time"] }
tracing = { workspace = true }

[build-dependencies]
bindgen = { workspace = true }
cmake = { workspace = true }
