[package]
name = "monad-mempool-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monad-mempool-controller = { path = "../monad-mempool-controller" }
monad-mempool-server = { path = "../monad-mempool-server" }

tokio = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
monad-mempool-types = { path = "../monad-mempool-types" }

ethers = { workspace = true }
hex = { workspace = true }
oorandom = { workspace = true }
