[package]
name = "monad-eth-txpool"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-eth-tx = { path = "../monad-eth-tx" }
monad-types = { path = "../monad-types" }

alloy-rlp = { workspace = true }
bytes = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
monad-multi-sig = { path = "../monad-multi-sig" }

alloy-primitives = { workspace = true }
criterion = { workspace = true, features = ["html_reports"] }
reth-primitives = { workspace = true }
rand = { workspace = true }
monad-types = { path = "../monad-types" }
monad-crypto = { path = "../monad-crypto" }

[[bench]]
name = "proposal_bench"
harness = false
