[package]
name = "monad-eth-txpool"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-eth-tx = { path = "../monad-eth-tx" }
monad-types = { path = "../monad-types" }

alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
bytes = { workspace = true }
itertools = { workspace = true }
reth-primitives = { workspace = true }
sorted_vector_map = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
criterion = { workspace = true, features = ["html_reports"] }
rand = { workspace = true }
rand_chacha = { workspace = true }
tracing-test = { workspace = true }

monad-crypto = { path = "../monad-crypto" }
monad-multi-sig = { path = "../monad-multi-sig" }
monad-perf-util = { path = "../monad-perf-util" }
monad-types = { path = "../monad-types" }

[[bench]]
name = "proposal_bench"
harness = false
