[package]
name = "monad-keystore"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[dependencies]
aes = { workspace = true }
ctr = { workspace = true }
hex = { workspace = true }
monad-crypto = { path = "../monad-crypto" }
pbkdf2 = { workspace = true, features = ["simple"] }
scrypt = { workspace = true, default-features = false }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
