[package]
name = "monad-tracing-timing"
version = "0.1.0"
edition = "2021"


[dependencies]
opentelemetry = { workspace = true, features = ["metrics"] }
opentelemetry_sdk = { workspace = true, features = ["metrics"] }
opentelemetry-otlp = { workspace = true }
quanta = { workspace = true }
tracing = { workspace = true, features = ["log"] }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }

[dev-dependencies]
opentelemetry_sdk = { workspace = true, features = ["testing"] }
futures = { workspace = true }
tokio =  { workspace = true, features = ["sync"] }