[package]
name = "monad-tracing-timing"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "timing_benchmark"
harness = false

[dependencies]
opentelemetry = { workspace = true, features = ["metrics"] }
opentelemetry_sdk = { workspace = true, features = ["metrics"] }
quanta = { workspace = true }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }

[dev-dependencies]
criterion = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["testing"] }
futures = { workspace = true }
tokio =  { workspace = true, features = ["sync"] }