#########################################################
#                                                       #
#        WARNING: THIS FILE SHOULD NEVER BE USED        #
#              IN PRODUCTION ENVIRONMENTS!              #
#                                                       #
#########################################################

#########################################################
# Node-specific configuration
#########################################################
beneficiary = "0x0000000000000000000000000000000000000000"
node_name = "dev-node"
network_name = "devnet"
ipc_tx_batch_size = 500
ipc_max_queued_batches = 6
# must be <= ipc_max_queued_batches
ipc_queued_batches_watermark = 3

statesync_threshold = 600
statesync_max_concurrent_requests = 5

#########################################################
# Network-wide configuration
#########################################################
chain_id = 20143

#########################################################
# Node-specific configuration
#########################################################
[bootstrap]
peers = []
# [[bootstrap.peers]]
# address = "x.x.x.x:xxxx"
# secp256k1_pubkey = "..."

[peer_discovery]
self_address = "0.0.0.0:8000"
self_record_seq_num = 0
self_name_record_sig = "7911fbf0df1307723c51658349ed396dd6ee28fde925277bae53fcd77705c4313e003a12fb562e1c20cc616511f7a09f986a3f6af6849cdedff6f5684557b04f01"
ping_period = 30
refresh_period = 120
request_timeout = 5
prune_threshold = 5
min_active_connections = 0
max_active_connections = 200
peers = []
# [[peer_discovery.peers]]
# address = "x.x.x.x:xxxx"
# record_seq_num = x
# secp256k1_pubkey = "..."
# name_record_sig = "..."

[fullnode]
identities = []
# [[fullnode.identities]]
# secp256k1_pubkey = "..."

[blocksync_override]
peers = []
# [[blocksync_override.peers]]
# secp256k1_pubkey = "..."

[statesync]
peers = []
# [[statesync.peers]]
# secp256k1_pubkey = "..."

[network]
bind_address_host = "0.0.0.0"
bind_address_port = 8000
max_rtt_ms = 300
max_mbps = 1000

#########################################################
# Network-wide configuration
#########################################################
[consensus]
execution_delay = 10
