#########################################################
#                                                       #
#        WARNING: THIS FILE SHOULD NEVER BE USED        #
#              IN PRODUCTION ENVIRONMENTS!              #
#                                                       #
#########################################################

beneficiary = "0x0000000000000000000000000000000000000000"

[bootstrap]
peers = []

# [[bootstrap.peers]]
# ip = "x.x.x.x"
# port = xxxx
# secp256k1_pubkey = "..."

[network]
bind_address_host = "0.0.0.0"
bind_address_port = 8888
max_rtt_ms = 5000
max_mbps = 1000
