#########################################################
#                                                       #
#        WARNING: THIS FILE SHOULD NEVER BE USED        #
#              IN PRODUCTION ENVIRONMENTS!              #
#                                                       #
#########################################################

beneficiary = "0x0000000000000000000000000000000000000000"
chain_id = 41454

[bootstrap]
peers = []

# [[bootstrap.peers]]
# address = "x.x.x.x:xxxx"
# mempool_address = "x.x.x.x:xxxx"
# secp256k1_pubkey = "..."

[consensus]
block_txn_limit = 10_000
block_gas_limit = 1_000_000_000
max_reserve_balance = 9_223_372_036_854_775_807
execution_delay = 10
reserve_balance_check_mode = 0

[network]
bind_address_host = "0.0.0.0"
bind_address_port = 8888
max_rtt_ms = 300
max_mbps = 1000
