[package]
name = "monad-blocktree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monad-consensus = { path = "../monad-consensus" }
monad-types = { path = "../monad-types" }
ptree = "0.4.0"

[dev-dependencies]
monad-testutil = { path = "../monad-testutil" }
monad-crypto = { path = "../monad-crypto" }
hex = "0.4"
