[package]
name = "monad-triedb"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
bindgen = { workspace = true }
cmake = { workspace = true }
