[package]
name = "monad-blockdb-utils"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
monad-blockdb = { path = "../monad-blockdb" }

heed = { workspace = true }
rayon = { workspace = true }
tokio = { workspace = true }
