[package]
name = "monad-consensus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[dependencies]
monad-crypto = { path = "../monad-crypto" }
monad-types = { path = "../monad-types" }
monad-validator = { path = "../monad-validator" }

sha2 = "0.10.6"
test-case = "3.0.0"
zerocopy = "0.6.1"
tracing = "0.1"

[dev-dependencies]
monad-testutil = { path = "../monad-testutil"}
