[package]
name = "monad-exec-events"
description = "Rust API for consuming execution events"
version = "0.1.0"
edition = "2021"


[dependencies]
monad-event-ring = { workspace = true }

chrono = { workspace = true }
clap = { workspace = true, features = ["derive"] }
hex = { workspace = true }
libc = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true }
tracing = { workspace = true }
zstd = { workspace = true }

[build-dependencies]
bindgen = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "snapshot"
harness = false
