name: Randomized Rust Test

on:
  schedule:
    - cron: '0 4 * * *' # run at 4 AM UTC
env:
  CARGO_TERM_COLOR: always
  ALL_MESSAGES_DELAYED_ROUND: 100
  NODES_WITH_RANDOM_LATENCY_ROUND: 100
  LEDGER_COMMAND_ARBITRARY_ORDER_ROUND: 100
jobs:
  build:
    runs-on: ubuntu-24.04-32
    steps:
    - name: Generate a token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.REPO_READONLY_GITHUB_APP_ID }}
        private_key: ${{ secrets.REPO_READONLY_GITHUB_APP_KEY }}
        permissions: >-
          {"contents": "read"}
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ steps.generate_token.outputs.token }}
    - run: rustup toolchain install nightly --profile minimal --component rustfmt
    - uses: Swatinem/rust-cache@v2
    - name: set rand env
      run: echo "RANDOM_TEST_SEED=$((RANDOM))" >> $GITHUB_ENV
    - name: Run all ignored test
      run:  cargo test cron -- --ignored  --nocapture
