name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install nightly --profile minimal --component rustfmt
      - name: Format
        run: cargo +nightly fmt --all --check --verbose
      - uses: Swatinem/rust-cache@v2
      - name: Lint
        run: cargo clippy --all-targets --all-features --
          -D clippy::suspicious
          -D clippy::style
          -D clippy::clone_on_copy
          -D clippy::redundant_clone
          -D clippy::iter_kv_map
          -D clippy::unnecessary_cast
          -D clippy::filter_next
          -D clippy::needless_lifetimes
          -D clippy::useless_conversion
          -D clippy::needless_question_mark
          -D clippy::bool_comparison
          -D unused_imports
          -D unused_parens
          -A clippy::type_complexity
          -A clippy::int_plus_one
          -A clippy::uninlined-format-args
      - name: Check
        run: cargo check --all-targets --all-features --verbose
      - name: Run tests
        run: cargo test --all-targets --all-features --verbose
