name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04-32

    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.REPO_READONLY_GITHUB_APP_ID }}
          private_key: ${{ secrets.REPO_READONLY_GITHUB_APP_KEY }}
          permissions: >-
            {"contents": "read"}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ steps.generate_token.outputs.token }}
      - run: rustup toolchain install nightly-2024-12-10 --profile minimal --component rustfmt
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Install cargo-shear
        run: cargo binstall --no-confirm cargo-shear
      - name: Lint unused dependencies
        run: cargo shear
      - name: Format
        run: cargo +nightly-2024-12-10 fmt --all --check
      - uses: Swatinem/rust-cache@v2
      - name: Lint
        run: cargo clippy --all-targets --all-features --
          -D clippy::suspicious
          -D clippy::style
          -D clippy::clone_on_copy
          -D clippy::redundant_clone
          -D clippy::iter_kv_map
          -D clippy::iter_nth
          -D clippy::unnecessary_cast
          -D clippy::filter_next
          -D clippy::needless_lifetimes
          -D clippy::useless_conversion
          -D clippy::useless_vec
          -D clippy::needless_question_mark
          -D clippy::bool_comparison
          -D unused_imports
          -D unused_parens
          -D deprecated
          -A clippy::type_complexity
          -A clippy::int_plus_one
          -A clippy::uninlined-format-args
          -A clippy::enum-variant-names
          -A clippy::mutable_key_type
      - name: Check
        run: cargo check --all-targets --all-features
      - name: Run tests
        run: cargo test --release --all-targets --all-features
      - name: Run doc tests
        run: cargo test --release --doc --all-features
      - run: rustup target add wasm32-unknown-unknown
      - name: Check WASM
        run: cargo check --target wasm32-unknown-unknown -p monad-debugger
