name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    types: [ opened, synchronize, reopened, edited ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04-32

    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.REPO_READONLY_GITHUB_APP_ID }}
          private_key: ${{ secrets.REPO_READONLY_GITHUB_APP_KEY }}
          permissions: >-
            {"contents": "read"}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ steps.generate_token.outputs.token }}
      - run: rustup toolchain install nightly-2024-12-10 --profile minimal --component rustfmt
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Install cargo-shear
        run: cargo binstall --no-confirm cargo-shear
      - name: Lint unused dependencies
        run: cargo shear
      - name: Format
        run: cargo +nightly-2024-12-10 fmt --all --check
      - uses: Swatinem/rust-cache@v2
      - name: Install C++ dependencies
        run: |
          sudo apt update && sudo apt upgrade -y

          sudo apt update && sudo apt install -y apt-utils
        
          sudo apt update && sudo apt install -y dialog
        
          sudo apt update && sudo apt install -y \
            ca-certificates \
            curl \
            gnupg \
            software-properties-common \
            wget
        
          sudo mkdir -p /opt
          sudo cp -r monad-cxx/monad-execution/scripts/ubuntu-build/* /opt/
        
          sudo apt update && sudo apt install -y \
            clang-18 \
            gcc-13 \
            g++-13
        
          sudo /opt/install-boost.sh
          sudo /opt/install-tools.sh
          sudo /opt/install-deps.sh
        
          sudo apt update && sudo apt install -y \
            libarchive-dev \
            libbrotli-dev \
            libcap-dev \
            libcli11-dev \
            libgmp-dev \
            libtbb-dev \
            libzstd-dev
      - name: Setup Hugepage
        run: |
          cat /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
          cat /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages
          sudo bash -c "echo 2048 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages"
          sudo bash -c "echo 4 > /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages"
          cat /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
          cat /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages
      - name: Lint
        run: ASMFLAGS="-march=haswell" CXXFLAGS="-march=haswell -DQUILL_ACTIVE_LOG_LEVEL=QUILL_LOG_LEVEL_CRITICAL" CFLAGS="-march=haswell" cargo clippy --all-targets --all-features --
          -D clippy::suspicious
          -D clippy::style
          -D clippy::clone_on_copy
          -D clippy::redundant_clone
          -D clippy::iter_kv_map
          -D clippy::iter_nth
          -D clippy::unnecessary_cast
          -D clippy::filter_next
          -D clippy::needless_lifetimes
          -D clippy::useless_conversion
          -D clippy::useless_vec
          -D clippy::needless_question_mark
          -D clippy::bool_comparison
          -D unused_imports
          -D unused_parens
          -D deprecated
          -A clippy::type_complexity
          -A clippy::int_plus_one
          -A clippy::uninlined-format-args
          -A clippy::enum-variant-names
          -A clippy::mutable_key_type
      - name: Check
        run: ASMFLAGS="-march=haswell" CXXFLAGS="-march=haswell -DQUILL_ACTIVE_LOG_LEVEL=QUILL_LOG_LEVEL_CRITICAL" CFLAGS="-march=haswell" cargo check --all-targets --all-features
      - name: Run tests
        run: ASMFLAGS="-march=haswell" CXXFLAGS="-march=haswell -DQUILL_ACTIVE_LOG_LEVEL=QUILL_LOG_LEVEL_CRITICAL" CFLAGS="-march=haswell" cargo test --release --all-targets --all-features
      - name: Run doc tests
        run: ASMFLAGS="-march=haswell" CXXFLAGS="-march=haswell -DQUILL_ACTIVE_LOG_LEVEL=QUILL_LOG_LEVEL_CRITICAL" CFLAGS="-march=haswell" cargo test --release --doc --all-features
      - run: rustup target add wasm32-unknown-unknown
      - name: Check WASM
        run: ASMFLAGS="-march=haswell" CXXFLAGS="-march=haswell -DQUILL_ACTIVE_LOG_LEVEL=QUILL_LOG_LEVEL_CRITICAL" CFLAGS="-march=haswell" cargo check --target wasm32-unknown-unknown -p monad-debugger
