name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Check
      run: cargo check --all-targets --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Lint
      run: >
        cargo clippy --tests --
        -A clippy::type_complexity
        -A clippy::int_plus_one
        -D clippy::suspicious
        -D clippy::style
        -D clippy::clone_on_copy
        -D clippy::redundant_clone
        -D clippy::iter_kv_map
        -D clippy::unnecessary_cast
        -D clippy::filter_next
        -D clippy::needless_lifetimes
        -D clippy::useless_conversion
        -D clippy::needless_question_mark
        -D clippy::bool_comparison
        -D unused_imports
        -D unused_parens
