[package]
name = "monad-triedb-cache"
version = "0.1.0"
edition = "2021"

[features]
test-utils = []

[lib]
bench = false

[dependencies]
monad-crypto = { path = "../monad-crypto" }
monad-state-backend = { path = "../monad-state-backend" }
monad-eth-types = { path = "../monad-eth-types" }
monad-types = { path = "../monad-types" }

alloy-rlp = { workspace = true }
bytes = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
