[package]
name = "monad-triedb-cache"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
monad-crypto = { path = "../monad-crypto" }
monad-eth-reserve-balance = { path = "../monad-eth-reserve-balance" }
monad-eth-types = { path = "../monad-eth-types" }
monad-types = { path = "../monad-types" }

alloy-rlp = { workspace = true }
bytes = { workspace = true }
rand = { workspace = true }
sorted_vector_map = { workspace = true }
tracing = { workspace = true }
