[package]
name = "monad-wal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monad-executor = { version = "0.1.0", path = "../monad-executor" }

[dev-dependencies]
monad-consensus = { path = "../monad-consensus"}
monad-crypto = { path = "../monad-crypto" }
monad-executor = { path = "../monad-executor" }
monad-state = { path = "../monad-state", features = ["proto"] }
monad-testutil = { path = "../monad-testutil" }
monad-types = { path = "../monad-types" }
tempfile = "3.5.0"
