[package]
name = "monad-mempool-txpool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monad-mempool-types = { path = "../monad-mempool-types" }

ethers = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
oorandom = { workspace = true }
